export default {
  testEnvironment: 'jsdom',
  testPathIgnorePatterns: [
    '/node_modules',
    '_modelo',
    'src/utils/',
    'src/ts/',
    'src/redux/',
    'src/routes/',
    'src/services/',
    'src/styles/',
  ],
  collectCoverage: true,
  collectCoverageFrom: [
    'src/**/*.tsx',
    '!src/**/*.ts',
    '!src/store/**/*.{ts,tsx}',
    '!src/react-app-env.d.ts',
    '!src/reportWebVitals.ts',
    '!src/setupTests.ts',
    '!src/index.{ts,tsx}',
    '!src/App.{ts,tsx}',
  ],
  coveragePathIgnorePatterns: [
    'src/hooks/index.{ts,tsx}',
    'src/index.{ts,tsx}',
    'src/App.{ts,tsx}',
    'src/utils/',
    'src/ts/',
    'src/redux/',
    'src/routes/',
    'src/services/',
    'src/styles/',
    '_modelo/',
  ],
  setupFilesAfterEnv: ['<rootDir>/.jest/setup.ts'],
  modulePaths: ['<rootDir>/src/', '<rootDir>/.jest'],
  transform: {
    '^.+\\.tsx?$': 'ts-jest',
  },
}
